$(document).ready(function(){
    $("button").click(function(){
        $("#div1").fadeIn("slow");
        $("#div2").fadeIn("fast");
        $("#div3").fadeIn(800);
        $("#div4").fadeIn(2000);
        $("#div5").fadeIn(4000);
    });
});